version: '3.9'

services:
  backend:
    build: .
    container_name: wnwn-backend
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: ["npm", "run", "dev"]

  db:
    image: postgres:15
    container_name: wnwn-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: